# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 22:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Armor_Proficiency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('armor_type', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alignment', models.CharField(choices=[('LG', 'Lawful Good'), ('G', 'Good'), ('CG', 'Chaotic Good'), ('LN', 'Lawful Nuetral'), ('N', 'Nuetral'), ('CN', 'Chaotic Nuetral'), ('LE', 'Lawful Evil'), ('E', 'Evil'), ('CE', 'Chaotic Evil')], default='N', max_length=256)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('age', models.PositiveSmallIntegerField(default=25)),
                ('hair_color', models.CharField(max_length=256)),
                ('deity', models.CharField(max_length=256)),
                ('height', models.CharField(max_length=256)),
                ('experience_points', models.PositiveIntegerField()),
                ('languages', models.CharField(max_length=256)),
                ('personality_traits', models.TextField()),
                ('ideals', models.TextField(null=True)),
                ('flaws', models.TextField(null=True)),
                ('bonds', models.TextField(null=True)),
                ('bio', models.TextField(null=True)),
                ('strength', models.PositiveSmallIntegerField(default=10)),
                ('dexterity', models.PositiveSmallIntegerField(default=10)),
                ('constitution', models.PositiveSmallIntegerField(default=10)),
                ('intelligence', models.PositiveSmallIntegerField(default=10)),
                ('wisdom', models.PositiveSmallIntegerField(default=10)),
                ('charisma', models.PositiveSmallIntegerField(default=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('hit_die', models.CharField(choices=[('4', '4'), ('6', '6'), ('8', '8'), ('12', '12')], default='6', max_length=256)),
                ('ability_score_improvement_levels', models.CommaSeparatedIntegerField(max_length=30)),
                ('weapon_type_prof', models.CharField(max_length=256)),
                ('armor_prof', models.ManyToManyField(to='tavern.Armor_Proficiency')),
            ],
        ),
        migrations.CreateModel(
            name='Class_Features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20')], default=1, max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('f_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tavern.Class')),
            ],
        ),
        migrations.CreateModel(
            name='Feats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('ability_increase', models.CharField(choices=[('STR', 'Strength'), ('DEX', 'Dexterity'), ('WIS', 'Wisdom'), ('INT', 'Intelligence'), ('CHA', 'Charisma'), ('CON', 'Constitution')], max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Martial_Melee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon_type', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Martial_Ranged',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon_type', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('T', 'Tiny'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('H', 'Huge'), ('G', 'Gargantuan')], default='S', max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('speed', models.PositiveSmallIntegerField(default=20)),
                ('vision', models.CharField(default='normal', max_length=100)),
                ('str_mod', models.PositiveSmallIntegerField(default=0)),
                ('dex_mod', models.PositiveSmallIntegerField(default=0)),
                ('wis_mod', models.PositiveSmallIntegerField(default=0)),
                ('int_mod', models.PositiveSmallIntegerField(default=0)),
                ('cha_mod', models.PositiveSmallIntegerField(default=0)),
                ('con_mod', models.PositiveSmallIntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('Languages', models.ManyToManyField(to='tavern.Languages')),
                ('armor_proficiencies', models.ManyToManyField(to='tavern.Armor_Proficiency')),
                ('martial_melee_prof', models.ManyToManyField(to='tavern.Martial_Melee')),
                ('martial_ranged_prof', models.ManyToManyField(to='tavern.Martial_Ranged')),
            ],
        ),
        migrations.CreateModel(
            name='Race_Features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20')], default=1, max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('f_race', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tavern.Race')),
            ],
        ),
        migrations.CreateModel(
            name='Simple_Melee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon_type', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Simple_Ranged',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon_type', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Skill_Proficiencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Spells',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20')], default=1, max_length=256)),
                ('school', models.CharField(choices=[('Abj', 'Abjuration'), ('Conj', 'Conjuration'), ('Div', 'Divination'), ('Ench', 'Enchantment'), ('Ill', 'Illusion'), ('Necro', 'Necromancy'), ('Trans', 'Transmutaion')], default='Abj', max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('duration', models.CharField(max_length=256)),
                ('casting_time', models.CharField(max_length=256)),
                ('range', models.CharField(max_length=256)),
                ('v', models.BooleanField()),
                ('s', models.BooleanField()),
                ('m', models.BooleanField()),
                ('component_desc', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='race',
            name='simple_melee_prof',
            field=models.ManyToManyField(to='tavern.Simple_Melee'),
        ),
        migrations.AddField(
            model_name='race',
            name='simple_ranged_prof',
            field=models.ManyToManyField(to='tavern.Simple_Ranged'),
        ),
        migrations.AddField(
            model_name='race',
            name='skill_prof',
            field=models.ManyToManyField(to='tavern.Skill_Proficiencies'),
        ),
        migrations.AddField(
            model_name='class',
            name='martial_melee_prof',
            field=models.ManyToManyField(to='tavern.Martial_Melee'),
        ),
        migrations.AddField(
            model_name='class',
            name='martial_ranged_prof',
            field=models.ManyToManyField(to='tavern.Martial_Ranged'),
        ),
        migrations.AddField(
            model_name='class',
            name='simple_melee_prof',
            field=models.ManyToManyField(to='tavern.Simple_Melee'),
        ),
        migrations.AddField(
            model_name='class',
            name='simple_ranged_prof',
            field=models.ManyToManyField(to='tavern.Simple_Ranged'),
        ),
        migrations.AddField(
            model_name='class',
            name='skill_prof',
            field=models.ManyToManyField(to='tavern.Skill_Proficiencies'),
        ),
        migrations.AddField(
            model_name='character',
            name='feats',
            field=models.ManyToManyField(to='tavern.Feats'),
        ),
        migrations.AddField(
            model_name='character',
            name='main_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tavern.Class'),
        ),
        migrations.AddField(
            model_name='character',
            name='race',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tavern.Race'),
        ),
    ]
