# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tavern', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('armor_type', models.CharField(choices=[('Light', 'Light'), ('Medium', 'Medium'), ('Heavy', 'Heavy'), ('Shield', 'Shield')], max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('armor_class', models.PositiveIntegerField(default=12)),
                ('strength', models.PositiveIntegerField(default=0)),
                ('disadvantage', models.BooleanField(default=False)),
                ('cost', models.PositiveIntegerField(default=40)),
                ('weight', models.PositiveIntegerField(default=20)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('cost', models.PositiveIntegerField(default=2)),
                ('weight', models.PositiveIntegerField(default=2)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Melee_Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Simple', 'Simple'), ('Martial', 'Martial')], default='Simple', max_length=256)),
                ('damage_type', models.CharField(choices=[('Bludgeoning', 'Bludgeoning'), ('Slashing', 'Slashing'), ('Piercing', 'Piercing')], max_length=256)),
                ('hit_die', models.CharField(choices=[('4', '4'), ('6', '6'), ('8', '8'), ('12', '12')], max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('cost', models.SmallIntegerField(default=10)),
                ('range', models.CommaSeparatedIntegerField(max_length=20)),
                ('weight', models.IntegerField(default=3)),
                ('description', models.TextField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ranged_Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Simple', 'Simple'), ('Martial', 'Martial')], default='Simple', max_length=256)),
                ('damage_type', models.CharField(choices=[('Bludgeoning', 'Bludgeoning'), ('Slashing', 'Slashing'), ('Piercing', 'Piercing')], max_length=256)),
                ('hit_die', models.CharField(choices=[('4', '4'), ('6', '6'), ('8', '8'), ('12', '12')], max_length=256)),
                ('cost', models.SmallIntegerField(default=10)),
                ('range', models.CommaSeparatedIntegerField(max_length=20)),
                ('description', models.TextField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weapon_Properties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='ranged_weapon',
            name='properties',
            field=models.ManyToManyField(to='tavern.Weapon_Properties'),
        ),
        migrations.AddField(
            model_name='melee_weapon',
            name='properties',
            field=models.ManyToManyField(to='tavern.Weapon_Properties'),
        ),
    ]
