# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tavern', '0003_auto_20160614_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
