# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tavern', '0006_auto_20160614_1616'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Armor_Proficiency',
            new_name='ArmorProficiency',
        ),
        migrations.RenameModel(
            old_name='Class_Features',
            new_name='ClassFeatures',
        ),
        migrations.RenameModel(
            old_name='Simple_Ranged',
            new_name='MartialMelee',
        ),
        migrations.RenameModel(
            old_name='Skill_Proficiencies',
            new_name='MartialRanged',
        ),
        migrations.RenameModel(
            old_name='Melee_Weapon',
            new_name='MeleeWeapon',
        ),
        migrations.RenameModel(
            old_name='Race_Features',
            new_name='RaceFeatures',
        ),
        migrations.RenameModel(
            old_name='Ranged_Weapon',
            new_name='RangedWeapon',
        ),
        migrations.RenameModel(
            old_name='Simple_Melee',
            new_name='SimpleMelee',
        ),
        migrations.RenameModel(
            old_name='Martial_Melee',
            new_name='SimpleRanged',
        ),
        migrations.RenameModel(
            old_name='Weapon_Properties',
            new_name='SkillProficiencies',
        ),
        migrations.RenameModel(
            old_name='Martial_Ranged',
            new_name='WeaponProperties',
        ),
        migrations.RenameField(
            model_name='martialranged',
            old_name='name',
            new_name='weapon_type',
        ),
        migrations.RenameField(
            model_name='weaponproperties',
            old_name='weapon_type',
            new_name='name',
        ),
    ]
