# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tavern', '0008_auto_20160614_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='meleeweapon',
            name='Denomination',
            field=models.CharField(choices=[('sp', 'Sp'), ('gp', 'Gp')], default='gp', max_length=256),
        ),
    ]
