# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tavern', '0009_meleeweapon_denomination'),
    ]

    operations = [
        migrations.AddField(
            model_name='armor',
            name='Denomination',
            field=models.CharField(choices=[('sp', 'Sp'), ('gp', 'Gp')], default='gp', max_length=256),
        ),
        migrations.AddField(
            model_name='armor',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='classfeatures',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='feats',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='Denomination',
            field=models.CharField(choices=[('sp', 'Sp'), ('gp', 'Gp')], default='gp', max_length=256),
        ),
        migrations.AddField(
            model_name='item',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='racefeatures',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='rangedweapon',
            name='Denomination',
            field=models.CharField(choices=[('sp', 'Sp'), ('gp', 'Gp')], default='gp', max_length=256),
        ),
        migrations.AddField(
            model_name='spells',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='meleeweapon',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='meleeweapon',
            name='range',
            field=models.CommaSeparatedIntegerField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='rangedweapon',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
