# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tavern', '0010_auto_20160614_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rangedweapon',
            name='range',
            field=models.CommaSeparatedIntegerField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='spells',
            name='range',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
