# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tavern', '0012_auto_20160614_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meleeweapon',
            name='properties',
            field=models.ManyToManyField(blank=True, to='tavern.WeaponProperties'),
        ),
    ]
