# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tavern', '0013_auto_20160614_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='rangedweapon',
            name='name',
            field=models.CharField(default='name', max_length=256),
        ),
    ]
