# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tavern', '0014_rangedweapon_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meleeweapon',
            name='Denomination',
            field=models.CharField(choices=[('cp', 'Cp'), ('sp', 'Sp'), ('gp', 'Gp')], default='gp', max_length=256),
        ),
        migrations.AlterField(
            model_name='rangedweapon',
            name='Denomination',
            field=models.CharField(choices=[('cp', 'Cp'), ('sp', 'Sp'), ('gp', 'Gp')], default='gp', max_length=256),
        ),
    ]
