# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tavern', '0016_rangedweapon_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='hit_die',
            field=models.CharField(choices=[('D4', 'D4'), ('D6', 'D6'), ('D8', 'D8'), ('d10', 'D10'), ('D12', 'D12'), ('2D6', '2D6')], default='D6', max_length=256),
        ),
        migrations.AlterField(
            model_name='meleeweapon',
            name='hit_die',
            field=models.CharField(choices=[('D4', 'D4'), ('D6', 'D6'), ('D8', 'D8'), ('D12', 'D12'), ('2D6', '2D6')], max_length=256),
        ),
        migrations.AlterField(
            model_name='rangedweapon',
            name='hit_die',
            field=models.CharField(choices=[('D4', 'D4'), ('D6', 'D6'), ('D8', 'D8'), ('D10', 'D10'), ('D12', 'D12'), ('2D6', '2D6')], max_length=256),
        ),
    ]
