# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tavern', '0020_auto_20160615_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='background',
            field=models.CharField(choices=[('Acolyte', 'Acolyte'), ('Criminal', 'Criminal'), ('Folk Hero', 'Folk Hero'), ('Noble', 'Noble'), ('Sage', 'Sage'), ('Soilder', 'Soilder')], default='Noble', max_length=256),
        ),
    ]
