# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tavern', '0023_character_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spells',
            name='m',
        ),
        migrations.RemoveField(
            model_name='spells',
            name='s',
        ),
        migrations.RemoveField(
            model_name='spells',
            name='v',
        ),
        migrations.AddField(
            model_name='spells',
            name='components',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='spells',
            name='level',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default='1', max_length=256),
        ),
    ]
