# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-17 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tavern', '0024_auto_20160617_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='MagicItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Magic Item', max_length=256)),
                ('type', models.CharField(choices=[('Armor', 'Armor'), ('Potion', 'Potion'), ('Ring', 'Ring'), ('Rod', 'Rod'), ('Scroll', 'Scroll'), ('Staff', 'Staff'), ('Wand', 'Wand'), ('Weapon', 'Weapon'), ('Wondrous Item', 'Wondrous Item')], default='Wondrous Item', max_length=256)),
                ('rarity', models.CharField(choices=[('Common', 'Common'), ('Uncommon', 'Uncommon'), ('Rare', 'Rare'), ('Very Rare', 'Very Rare'), ('Legendary', 'Legendary')], default='Rare', max_length=256)),
                ('attunement', models.CharField(blank=True, max_length=256, null=True)),
                ('notes', models.CharField(blank=True, max_length=1000, null=True)),
                ('source', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='spells',
            name='spell_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tavern.Class'),
        ),
        migrations.AlterField(
            model_name='spells',
            name='level',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default='0', max_length=256),
        ),
    ]
